### ISSUE TITLE
Smooth continuous loading?

### ISSUE THREAD

**Issue by lightninglu10** [klendi/react-top-loading-bar#1]
Hey @klendi is there anyway to set a smooth continuous loading? 

Like if we want the bar to complete after 5s, what we're doing now is just setting an interval to increase the bar by 1 every 50ms. It's not a super smooth experience though. Anything you suggest?

**Comment by klendi** [comment]
Hello.
You can do the loading smoothness however you want because you control the direct value of the loading bar with the progress property. What we can do is automate the process, I mean that since we signal the loading bar that the loading started the loading bar takes care of himself and smoothly increase near 100%, but never reach it. It only reaches 100% when we signal it that the loading is done. Like YouTube does. Like a fake loading bar that has no idea what is happening but just know when to start and when to reach 100%, with events. Yeah I have been thinking about that. And I have a idea how to do it. I will work on it or you can if you wish :)

**Comment by klendi** [comment]
Hey @lightninglu10 just added the feature you requested (continuous loading bar) and much more in the latest commit. Now you don't need to set up a local state, you can use ref and built in methods. Although this is optional. You still can use the old way with props and state.
