### ISSUE TITLE
Make it work with typescript

### ISSUE THREAD

**Issue by LiamDotPro** [klendi/react-top-loading-bar#19]

**Comment by klendi** [comment]
Yes I did that. Made the index.js to index.tsx but yeah you're right I don't need autocomplete too etc. Perhaps need to add types manually.

**Comment by LiamDotPro** [comment]
The problem is that your distribution doesn't include typings for the outputted component, this means anyone importing this component via NPM is lacking types to use inside they're project.

**Comment by klendi** [comment]
A new typescript rewrite is coming soon. Will fix the auto complete problem

**Comment by SeinopSys** [comment]
This appears to be the best loader library I found so far, do you still plan to create the TypeScript rewrite?

**Comment by klendi** [comment]
Yes it's 90% done, it's branch "v2", but it still need a little bit of work to make backwards compatible with the current version, not just typescript but a total rewrite. I haven't worked much on it since I have been very busy with work and now it's vacations time. Perhaps can work a little bit tonight.

You are welcome to collaborate / contribute to the project.

**Comment by klendi** [comment]
So I stayed up a little bit and finished it and deployed it. You can check the new version in here https://klendi.github.io/react-top-loading-bar/ and npm. Thank you.

The new version is written in TS.
