### ISSUE TITLE
Wrong TS typings for LoadingBarRef's continuousStart method

### ISSUE THREAD

**Issue by Thanaen** [klendi/react-top-loading-bar#53]
Repro: https://codesandbox.io/s/react-top-loading-bar-typing-kxsdn

It seems that the `continuousStart` typings have recently been updated. The method now requires two mandatory paramters "startingValue" and "refreshRate". 
The method's type is currently:
```ts
((startingValue: number, refreshRate: number) => void) | undefined
```

Shouldn't it be:
```ts
((startingValue?: number, refreshRate?: number) => void) | undefined
```
?

**Comment by baumerdev** [comment]
Yes, kind of … at least that's what the docs say (both params optional).

But since the method signature is `continuousStart(startingValue: number, refreshRate: number = 1000)` this should be changed to `continuousStart(startingValue?: number, refreshRate: number = 1000)` to make method and type match.

https://github.com/klendi/react-top-loading-bar/blob/master/src/index.tsx#L113
